# Generated by Django 2.1.1 on 2018-09-30 14:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text', '0002_text_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
