# Generated by Django 2.1.2 on 2018-10-20 15:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('text', '0003_auto_20181011_1908'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(db_index=True, max_length=500)),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('text', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='text.Text')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
