# Generated by Django 2.1.2 on 2018-10-09 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(db_index=True, max_length=100)),
                ('text', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='code.Text')),
            ],
        ),
    ]
