# Generated by Django 2.1.2 on 2018-10-11 14:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code', '0002_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='text',
            name='date',
        ),
        migrations.AddField(
            model_name='text',
            name='date_creation',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='text',
            name='date_last_change',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='text',
            name='topic',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
