# Generated by Django 2.1.2 on 2018-11-10 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code', '0005_auto_20181029_0021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='text',
            field=models.CharField(max_length=10000),
        ),
    ]
